nextcloud/talk-desktop

src/patchers/nextcloud-auth.js
* Issue #70
In provisioning API `getUser` and `getCurrentUser` methods returns display name with a different property name.
In this PR `@nextcloud/auth/getCurrentUser` tries both properties considering the current name as "legacy".
Related: https://github.com/nextcloud/server/pull/36665
=> Fix wrong display-name property from provisioning getUser response

src/patchers/nextcloud-notify_push.js, src/talk/renderer/notifications/notifications.store.js
=> Fix loosing authentication on notify_push on any ws error

src/app/app.menu.js, src/app/applyWheelZoom.js, src/talk/talk.window.js
* Issue #74
By default an Electron application has "CommandOrControl + Plus" hotkey for zooming in. It is not very  intuitive, that without SHIFT pressing "CommandOrControl + Plus" actually works as "CommandOrControl + =". 
Adding invisible menu item to add hotkey alias may look wierd. But it seems to be a common practice to solve this problem in Electron applicatoin in a simple and reliable way.
Also, it was possible to change the hotkey in the existed menu item, but it would change displayed hotkey. This solution keeps displaying original hotkey in menu while both hotkeys works exactly the same.
=> Add CommandOrControl + Plus hotkey for zoomIn without SHIFT

src/app/webRequestInterceptor.js, src/talk/renderer/notifications/notifications.store.js
=> Fix missed notifications event bus emitting and notification request caching

src/help/help.window.js, src/help/renderer/HelpApp.vue
* Issue #102
---|---
By default and by design native modal windows on MacOS doesn't have controls and not closable.
=> Fix unclosable About window on Mac - make About window closable by Escape and a new close button

src/app/githubReleaseNotification.service.js, src/main.js
* Issue #124
No visual changes
=> Fix GitHub Rate Limit error: do not make unnecessary the latest new version requests

src/app/webRequestInterceptor.js
* Issue #73
Session is defined in cookies. Server may return cookies in different casing e.g. `set-cookie`, `Set-Cookie`, `SET_COOKIE`. Previously only `set-cookie` was checked (I used to think, Electron force all headers to lower case...).
In this PR interceptor finds all `/set-cookie/i` headers.
No changes
=> Fix session loosing caused by different `set-cookie` casing

CHANGELOG.md, package-lock.json, package.json
- Fix importing images to support video backgrounds in Nextcloud Talk 17
Built-in Talk in binaries is updated to 16.0.3. Talk changelog: https://github.com/nextcloud/spreed/releases/tag/v16.0.3
=> release: v0.3.2

src/patchers/nextcloud-initial-state.js
* Issue: support of https://github.com/nextcloud/spreed/pull/9436
=> fix(patchers): add highlight own group mentions support

src/patchers/nextcloud-router.js
There was a redundant `webroot` in `generateFilePath` patcher. `generateFilePath` already uses `webroot` which breaks some links.
It breaks loading one file: `/core/img/filetypes/file.svg`
=> fix(patchers): fix doubling webroot in generateFilePath

CHANGELOG.md, README.md, package-lock.json, package.json
- Fix doubling webroot cause failing loading the default file icon [#173](https://github.com/nextcloud/talk-desktop/pull/173)
- Allow MKCOL requests for creating virtual bg folder [#174](https://github.com/nextcloud/talk-desktop/pull/174)
- Fix initial state patching to add highlight own group mentions support [#171](https://github.com/nextcloud/talk-desktop/pull/171)
Built-in Talk in binaries is updated to new major 17.0.0-beta.1. Talk changelog: https://github.com/nextcloud/spreed/releases/tag/v17.0.0-beta.1
=> release: v0.4.0

CHANGELOG.md
Sorry, forgot to update the Talk's version from the previous graft.
=> chore(changelog): fix wrong Talk version

src/authentication/login.service.js
* Issue #199
---|---
P.S. Should it be mentioned in the loginFlow docs?
=> fix(auth): fix login for users with space in userid

src/authentication/login.window.js
* Should not be a regression, but for me it was like a regression of https://github.com/nextcloud/talk-desktop/pull/237
---|---
=> fix(authentication): Use content size on login web-view to avoid scroll on Windows

CHANGELOG.md, package-lock.json, package.json
Built-in Talk in binaries is updated to 17.0.1. Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
- Allow to log in with a copy-pasted URL from browser [#204](https://github.com/nextcloud/talk-desktop/pull/204)
- Fix capabilities update only with re-login [#198](https://github.com/nextcloud/talk-desktop/issues/198)
- Fix login for users with a space in userid [#199](https://github.com/nextcloud/talk-desktop/issues/199)
- Urldecode the app password [#203](https://github.com/nextcloud/talk-desktop/pull/203)
=> release: v0.7.0

src/app/appData.service.js
* Issue described in: https://github.com/nextcloud/talk-desktop/pull/254#issuecomment-1619642040
With invalid credentials, capabilities were infinitely re-fetching.
Drawbacks:
- In development mode, we cannot detect if there is a network error or authentication (CORS fails anyway for a failed request).
- Could there be another error that should also be a reset trigger?
- https://github.com/nextcloud/talk-desktop/issues/19 is still actual
=> Fix: catch errors on capabilities re-fetching

src/shared/resource.utils.js
Sometimes with a dark theme, some components act like a light theme.
The problem appears when Talk app initializes and starts faster than CSS with the user's theme is loaded.
(Currently, Talk detect dark theme by CSS)
`loadCss` util is supposed to be async and return a promise, but actually, it doesn't.
_This could be not the only problem with dark theme detection thus it also appears out of initial loading._
---|---
=> Fix incorrect dark theme detection caused by missing css load waiting

src/app/app.tray.js, src/main.js, src/talk/talk.window.js
Tray sometimes misses the window it is associated with and works inconsistently on different windows:
- Welcome and Login windows have tray icon, but the app doesn't stay in tray when a window is closed
- On logout the main talk window is closed but still exists in the memory as a leaked window process (because the tray keeps the window from being closed)
- After logout opening a login window from the tray crashes the app:
This PR changes the behavior of the Tray. Now the system tray icon is only used in main Talk app window, but is not used in Welcome loading screen and Login window.
=> fix(tray): use tray only in talk window and re-setup when window changes

CHANGELOG.md, package-lock.json, package.json
Built-in Talk in binaries is updated to 17.0.3. Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
=> release: v0.9.0

CHANGELOG.md, package-lock.json, package.json
- Add support for "Upgrade required" server response [#289](https://github.com/nextcloud/talk-desktop/pull/289)
Built-in Talk in binaries is updated to 17.1.0-rc.1. Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
=> release: v0.10.0

package-lock.json, package.json, webpack.renderer.config.js
Twin PR for https://github.com/nextcloud/spreed/pull/10055
If built-in Talk has `esbuild-loader` - use ESBuild loader, but with latest ES2022 (for Top-level await). Otherwise - use `babel-loader` as in the past.
Config looks a little bit complicated while both options are supported.
=> Add optional support for ESBuild

webpack.renderer.config.js
Build doesn't work with `stable27`. Check with by `require.resolve('esbuild-loader', { paths: [TALK_PATH] })` is not enough. If there is no `esbuild-loader` in Talk, it just finds it in the Talk Desktop.
=> build: fix checking for esbuild-loader in Talk

src/main.js
* Fix https://github.com/nextcloud/talk-desktop/issues/278
Currently when Talk Desktop executable is run:
- If it wasn't running - it starts
- If it is running - the window is focused
- If it is running but minimized - it is restored and the window is focused
- If it is running but minimized to the system tray and there is no window - nothing happened (it is the bug)
=> fix: restore app from system tray on reopen

src/app/appData.service.js, src/app/webRequestInterceptor.js, src/talk/renderer/init.js
Two related issues:
1. Sometimes start shows just the default background without any visible errors or menu when credentials are not valid anymore or the server is not available on start.
2. Sometimes on development it is not possible to handle if a request was not successful because of an authentication error or other problem.
- When `OPTIONS` request fails it is always just a general `Network error` for the client. The client cannot determine if it was actually a network error, authentication error or anything else
- `OPTIONS` request now always returns 200
- If there was an error, then actual request will fail later with an implicit error
- It's made a bit hacky. It is not possible to determine style loading error reason. I'm doing an additional general HTTP request to get the error.
- …
=> Fix: catch http errors on development and styles loading

CHANGELOG.md, package-lock.json, package.json
- Restore app from system tray on reopen by @ShGKme in [#348](https://github.com/nextcloud/talk-desktop/pull/348)
- Catch http errors on development and styles loading by @ShGKme in [#347](https://github.com/nextcloud/talk-desktop/pull/347)
- Built-in Talk in binaries is updated to v17.1.0 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
=> Release v0.11.0

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v17.1.1 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
=> chore(release): Add changelog for 0.12.0

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v17.1.2 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
=> release: v0.13.0

src/authentication/login.window.js, src/authentication/renderer/AuthenticationApp.vue, src/authentication/renderer/authentication.main.js, src/help/renderer/HelpApp.vue, src/help/renderer/help.app.js, src/main.js, src/preload.js, src/shared/setupWebPage.js, src/talk/renderer/init.js, src/talk/renderer/talk.main.js, src/upgrade/renderer/upgrade.app.js
* Fix #3 
* Fix #363
P.S. Translated by GitHub Copilot
=> fix: all windows l10n

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.0-beta.1 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
- Fix translations on Login, Help and Upgrade required windows [#363](https://github.com/nextcloud/talk-desktop/issues/363), [#3](https://github.com/nextcloud/talk-desktop/issues/3)
=> release: v0.14.0

src/patchers/@nextcloud/router.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/405
---|---
=> fix(patchers): add support for `.gif` images request for animated emojis

package-lock.json, package.json, src/patchers/OC/OcDialogsAdapter.vue, src/patchers/OC/dialogs.js, src/patchers/globals.js
=> fix(patchers): update `OC.dialogs` replacement with `NcDialog`-based adapter

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.0-beta.2 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
- Update confirm dialogs to use Nextcloud dialogs instead of native confirm [#12](https://github.com/nextcloud/talk-desktop/issues/12)
- Add support for `.gif` images request for animated emojis in call reactions [#405](https://github.com/nextcloud/talk-desktop/issues/405)
=> release: v0.15.0

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.0-beta.3 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
=> release: v0.16.0

src/main.js, src/talk/talk.window.js
* Fix #427
* Will be useful for #29
Welcome window is not hide. Hiding the welcome window is more problematic because the app is not in the system tray and connection could not be successful.
So for some time it is visible anyway.
=> feat: add `--background` argv support for opening app minimized to the system tray

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.0-rc.2 Talk changelog: https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md
- Add `--background` argv support for opening app minimized to the system tray [#427](https://github.com/nextcloud/talk-desktop/issues/427)
=> release: v0.17.0

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.0-rc.3
- l10n: replace triple dots with ellipsis [#450](https://github.com/nextcloud/talk-desktop/pull/450)
=> release: v0.18.0

src/main.js, src/shared/setupWebPage.js
`@nextcloud/l10n` expect `_` separator while OS may return `-`.
---|---
`de-DE` | `de_DE`
=> fix(authentication): system lang separator

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.1
- Fix language detection for some languages [#458](https://github.com/nextcloud/talk-desktop/pull/458)
=> release: v0.20.0

forge.config.js
9000 conflicts with Talk API
Used only to provide log from Webpack during development.
9005 checked on https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
=> chore(dev): change default Webpack logger port from 9000 for 9005

README.md, src/app/webRequestInterceptor.js, src/patchers/@nextcloud/axios.js, src/patchers/@nextcloud/initial-state.js
* FilePicker ("Share from Nextcloud") support. It should have been working after migrating to `@nextcloud/dialogs@5` but after some changes in `@nextcloud/dialogs` it hasn't been working again
- I have no idea why I deleted this header 😶
- Actually, it also allows requesting the contact menu for `NcAvatar`
=> fix: "Share from Nextcloud" support

forge.config.js, src/talk/renderer/init.js, src/talk/renderer/talk.main.js
Since Nextcloud 29 (Talk 19) 
How to test:
1. Open Talk Desktop
2. Change admin settings
3. In 30 seconds Talk Desktop should restart
4. Should work on `main` / `stable27` / `stable28`
=> fix(talk): support Pinia talkHashStore for Talk 19

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v18.0.4
- Fix window icon on linux [#308](https://github.com/nextcloud/talk-desktop/pull/308)
- Fix "Share from Nextcloud" support [#540](https://github.com/nextcloud/talk-desktop/pull/540)
- Allow avatar menu on desktop [Talk#11675](https://github.com/nextcloud/spreed/pull/11675)
- Added Nextcloud Talk 19 support
- Update dependencies
- Update translations
=> release: v0.22.0

src/talk/renderer/init.js
* Regression from https://github.com/nextcloud/talk-desktop/pull/542
* Thought, it works fine while importing module with `_esModule: true`...
=> fix(talk): correctly import Vuex store from Talk

package-lock.json, package.json, tsconfig.json, webpack.renderer.config.js
* Importing TS with ESM import without extensions in Talk source doesn't work in Talk Desktop, module not found.
```
ERROR in ./spreed/src/components/NewMessage/NewMessage.vue?vue&type=script&lang=js& (./node_modules/esbuild-loader/dist/index.cjs??clonedRuleSet-15!./node_modules/vue-loader/lib/index.js??vue-loader-options!./spreed/src/components/NewMessage/NewMessage.vue?vue&type=script&lang=js&) 25:0-101
Module not found: Error: Can't resolve '../../services/avatarService'
```
- This is not a good solution, but spending almost a full working day I have found no other solutions from the Talk Desktop side and I don't understand, why it doesn't work.
- Alternative - follow server style in Talk and always import with extensions. But it would require a new Talk release.
=> build: support TS in Talk

package-lock.json, package.json
* Revert of https://github.com/nextcloud/talk-desktop/pull/552 and pin on 6.6.2
* Somehow `undici@6.7.0` breaks production (and only production) build...
=> chore(deps): pin undici on 6.6.2

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v19.0.0-beta.1
- Fix Talk hash integration with Talk 18 and below [#550](https://github.com/nextcloud/talk-desktop/pull/550)
=> release: v0.23.0

package-lock.json, package.json
- https://github.com/nextcloud/talk-desktop/pull/562 was not supposed to happen
- See: https://github.com/nextcloud/talk-desktop/pull/552#issuecomment-1988667826
=> revert: "chore(deps): Bump undici from 6.6.2 to 6.7.1"

src/talk/renderer/talk.main.js
* Allows to remove special path alias for welcome page for Talk Desktop: https://github.com/nextcloud/spreed/pull/11877
* This doesn't require support (backport of mentioned PR) for old Talk versions
No visual changes
=> fix(talk): support original path for root page

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v19.0.0-beta.4
=> chore(release): Bump version to 0.25.0

CHANGELOG.md, package-lock.json, package.json
- Downgrade undici dependency again [#583](https://github.com/nextcloud/talk-desktop/pull/583)
- Built-in Talk in binaries is updated to v19.0.0-beta.5
=> Release v0.26.1

package-lock.json, package.json
- Bring back #557
- `undici` must be exact `6.6.2`, not `compatible with 6.6.2`
=> chore(deps): pin exact undici@6.6.2

README.md
* Supported since https://github.com/nextcloud/spreed/pull/11675
=> chore(readme): remove contacts menu from unsupported features list

src/constants.js, webpack.renderer.config.js
* We always build Talk Desktop with the latest released Talk
* Require only latest released stable version of Talk - currently 18
* Remove support for Babel in Webpack config used from Talk 17
=> build: drop support for building with Talk v17

.eslintrc.js, README.md, package-lock.json, package.json, src/main.js, src/preload.js, src/shared/os.utils.js, src/talk/renderer/AppGetDesktopMediaSource.vue, src/talk/renderer/components/DesktopMediaSourceDialog.vue, src/talk/renderer/components/DesktopMediaSourcePreview.vue, src/talk/renderer/getDesktopMediaSource.js, src/talk/renderer/talk.main.js
* Fix #11
- With live previews (except on Wayland)
- Supports "All screens with audio". All of the other options don't support audio streaming.
- When there is only one screen, the first option is renamed to "Entire screen with audio"
- On Mac - opens settings to allow screensharing if it is not allowed
https://github.com/nextcloud/talk-desktop/assets/25978914/7f29e4ec-86ca-4597-8e10-cfd5f79527fc
Wayland with PipeWire has a different workflow:
- Requesting all available sources (screens, windows) - triggers native system dialog to choose what to share
- Showing the stream for the selected source also triggers the system dialog
- So live preview for all options is not possible, each preview triggers the dialog
- Instead, only one static image preview is shown for the selected source
- …
=> feat: screen sharing

package-lock.json, package.json, src/patchers/@nextcloud/router.js, src/shared/globals/globals.js, src/talk/renderer/talk.main.js
`@nextcloud/router` cannot be used as it is, because it relies on `window.location` which is different on Desktop app.
- For functions returning relative link, `window._oc_webroot` was replaced with an absolute base path instead of relative (`https://nextcloud.ltd/cloud` instead of `/cloud`) to return an absolute link
- For functions returning an absolute link, a complete copy-pasting solution was made
It makes it impossible to work with relative links. And it is just not clean
`getBaseUrl` was literally the same as `getRootUrl`.
`_oc_webroot` is now kept original (relative) and only when needed temporally replaced with an absolute.
Added `OCA.Talk.Desktop.runWithAbsoluteWebroot` helper to run another function having absolute webroot.
`@nextcloud/router` is now patched with this helper …
=> fix(patchers): patch router without permanent absolute _oc_webroot

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v19.0.0-rc.3
- Add screensharing support [#11](https://github.com/nextcloud/talk-desktop/issues/11)
- Add image and video viewer support [#255](https://github.com/nextcloud/talk-desktop/issues/255)
- Open a conversation by link to other conversations in the app instead of a web-browser [#603](https://github.com/nextcloud/talk-desktop/pull/603)
- Open and create a 1-to-1 conversation by "Talk to User" from the participant's menu in the app instead of a web-browser [Talk#11879](https://github.com/nextcloud/spreed/pull/11879)
- Pretty "Copy conversation link" without "index.php" if supported by server for Nextcloud 29+ [#605](https://github.com/nextcloud/talk-desktop/issues/605)
=> release: v0.28.0

src/talk/renderer/components/DesktopMediaSourceDialog.vue, src/talk/renderer/components/DesktopMediaSourcePreview.vue
Yesterday during the call, I suddenly selected "Entire screen with audio" option, so other attendants heard themselves. This is not the options I wanted to choose, just mixed-up. And that's me who developed the feature 🙈 
---|---
Also, sometimes it was randomly in this order before:
=> fix(screensharing): better sort and name available sources

README.md, src/main.js, src/preload.js, src/shared/setupWebPage.js
* Multi-account support is covered by https://github.com/nextcloud/talk-desktop/issues/7
* But full multi-account support is not a simple feature...
* As a temporal workaround allow renaming executable to have several simultaneously running Talk Desktop instances
* Also useful for testing federations
```
/path/to/apps/
├── home-apps/
│   └── Nextcloud Talk/
│       ├── ...
│       ├── Nextcloud Talk (Home).exe
│       └── ...
└── work-apps/
└── Nextcloud Talk/
├── ...
├── Nextcloud Talk (Work).exe
└── ...
```
=> feat: workaround for multi-account support with several instance with different executable names

src/authentication/authentication.window.js, src/authentication/renderer/AuthenticationApp.vue, src/talk/renderer/DesktopHeader.vue, src/talk/renderer/Viewer/ViewerApp.vue, src/talk/renderer/assets/overrides.css, src/talk/renderer/components/UserMenu.vue, src/talk/renderer/desktop.app.js, src/talk/renderer/init.js, src/talk/renderer/talk.main.js, src/talk/talk.window.js, src/welcome/welcome.window.js
- Fix #377
https://github.com/nextcloud/talk-desktop/assets/25978914/30e24a44-7257-4f3e-bd3b-d69e0b591465
Before | After
---|---
Before | After
---|---
=> feat: new title bar design

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v19.0.0-rc.5
- New title bar design and other minor design changes [#617](https://github.com/nextcloud/talk-desktop/pull/617)
- Workaround for multi-account support with different executable names [#620](https://github.com/nextcloud/talk-desktop/pull/620)
- Better sort and name available screensharing sources [#618](https://github.com/nextcloud/talk-desktop/pull/618)
- Show mime type icon for attachments in messages [#619](https://github.com/nextcloud/talk-desktop/pull/619)
- Show main window after login [#623](https://github.com/nextcloud/talk-desktop/pull/623)
=> release: v0.29.0

src/talk/renderer/assets/styles.css
* Outline color is a bit unpredictable and may look weird
* Use `var(--color-main-text)` as a default value when it is not defined explicitly 
---|---
=> fix(talk): define default outline color for focus visible

src/main.js, src/preload.js, src/talk/renderer/notifications/notifications.store.js
* Issue #388
* Also fixed an issue when sometimes there was a race condition with Talk around adding `* ` to the title, which skipped icon flushing (see: https://github.com/nextcloud/talk-desktop/issues/291#issuecomment-2068721124)
=> feat(notifications): flash or bounce icon on new notification

scripts/prepare-release-packages.mjs
- ~~⚠️ Waiting for the release~~
- After https://github.com/nextcloud/talk-desktop/pull/602 `release:package` doesn't work on Windows. Manual setting `pwsh` (modern `PowerShell v7`) was replaced with `usePowerShell` that uses old unsupported and yet default one `PowerShell v5` instead of new `PowerShell v7+`.
```
At line:1 char:24
+ npm run package:windows && npm run make:windows; exit $LastExitCode
+                         ~~
The token '&&' is not a valid statement separator in this version.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine
```
This PR sets up `pwsh` with new `usePwsh` from `zx@8.1.0`.
=> build: use pwsh for release:package on Windows

src/shared/initialState.service.js, src/shared/setupWebPage.js, src/talk/renderer/UserStatus/userStatus.store.js, src/talk/renderer/init.js, src/talk/renderer/notifications/notifications.store.js, src/talk/renderer/talk.main.js
* Fix #415
- Defined by initial state
=> fix(notifications): disable sounds on DND

src/talk/talk.window.js
* The default window size is too small to fit the default join call dialog even without recording concern
* Increase the default window size
* Also make the default window size not more than 
---|---
=> fix(talk): increase window size to fit display and include join dialog

package-lock.json, package.json
* `AGPL-3.0` may mean both `AGPL-3.0-or-later` and `AGPL-3.0-only`.
* The product license is `AGPL-3.0-or-later`
* Source files are also in `AGPL-3.0-or-later`
* `package.json` and `package-lock.json` themself are `CC0-1.0`, the `license` field does not define their license.
https://github.com/nextcloud/talk-desktop/blob/ca8b1138d684bcb43f5a9d749f05b8f700e07bab/.reuse/dep5#L20-L23
* Also changed `author` format and email to match `AUTHORS.md`
=> chore(package): update author and license fields to match product license

src/shared/globals/globals.js, src/talk/renderer/DesktopHeader.vue, src/talk/renderer/UserStatus/components/UserStatusForm.vue, src/talk/renderer/components/MainMenu.vue, src/talk/renderer/components/ThemeLogo.vue, src/talk/renderer/components/UiMenuItem.vue, src/talk/renderer/components/UiMenuSeparator.vue, src/talk/renderer/components/UserMenu.vue, src/talk/renderer/talk.main.js
* Separate Menu to User Menu and Main Menu, making both simpler and smaller
* Improve the user menu:
* Display not only `displayName` but also `userid`
* Display also server name, link and icon
* Especially actual for users with multiple instances
* Improve the user status menu to make it easier to switch to DnD
* See discussions and drafts in https://github.com/nextcloud/talk-desktop/pull/650
* As a part of the menu rewriting - refactor to SFC Setup
---|---
. | ![image](https://github.com/nextcloud/talk-desktop/assets/25978914/ea676920-8114-463c-b90f-cb646c3c921f)
. | ![image](https://github.com/nextcloud/talk-desktop/assets/25978914/96907444-5ecd-4857-89a7-9b7ade797c88)
. | ![image](https://github.com/nextcloud/talk-desktop/assets/25978914/b253386f-1f07-4577-97b8-1ad4 …
=> fix(app): improve user menu design

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v19.0.2
- Add user status support [#26](https://github.com/nextcloud/talk-desktop/issues/26)
- Flash or bounce icon on a new notification [#388](https://github.com/nextcloud/talk-desktop/issues/388)
- Improve user menu design [#683](https://github.com/nextcloud/talk-desktop/pull/683)
- Make Talk Desktop user appears "online" on server [#634](https://github.com/nextcloud/talk-desktop/pull/634)
- Disable sounds on Do-Not-Disturb [#415](https://github.com/nextcloud/talk-desktop/issues/415)
- Increase the default window size to fit the display and include the join call dialog [#682](https://github.com/nextcloud/talk-desktop/pull/682)
- Define the default outline color for focus visible [#643](https://github.com/nextcloud/talk-desktop/pull/643)
=> release: v0.30.0

CHANGELOG.md, package-lock.json, package.json
* fix(DesktopHeader): make text and icons contrast by @Antreesy in https://github.com/nextcloud/talk-desktop/pull/703
* build(deps-dev): Bump zx from 8.1.3 to 8.1.4 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/705
* build(deps-dev): Bump eslint-plugin-promise from 6.2.0 to 6.4.0 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/708
* build(deps-dev): Bump eslint-plugin-vue from 9.26.0 to 9.27.0 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/707
- Built-in Talk in binaries is updated to v19.0.5 Talk changelog: https://github.com/nextcloud/spreed/blob/v19.0.5/CHANGELOG.md
=> Release v0.32.0

.eslintrc.js, src/authentication/renderer/AuthenticationApp.vue, src/help/renderer/HelpApp.vue, src/shared/globals/OC/OcDialogsAdapter.vue, src/shared/setupWebPage.js, src/talk/renderer/DesktopHeader.vue, src/talk/renderer/UserStatus/userStatus.service.js, src/talk/renderer/Viewer/ViewerApp.vue, src/talk/renderer/Viewer/ViewerHandlerImages.vue, src/talk/renderer/Viewer/ViewerHandlerVideos.vue, src/talk/renderer/components/UiMenu.vue, src/talk/renderer/components/UiMenuItem.vue, src/talk/renderer/components/UiMenuSeparator.vue, src/upgrade/renderer/UpgradeApp.vue
Follow 2022+ Vue recommendations and defaults:
- Migrate to Composition API
- Using SFC Setup as a new default recommendation and a place with better TS support with new features in Vue 3
- Change block order to `script, template`
- Places template close to styles
Add corresponding ESLint rules
=> refactor: migrate to Composition API with SFC Setup and new defaults

src/authentication/login.window.js
Step to reproduce:
1. Start the login process
2. Log in as **User1**
4. Before finishing the process, realize that you actually wanted to log in as User2
6. Close the login WebView
7. Open again
- **Expected**: You can log in as User2
- **Actual**: You are still logged in as User1 and can only grant access to Talk Desktop
Note: `non-persist` stores partition until app restart, not window reopening.
=> fix(authentication): create a new cache partition on open login web-view

src/patchers/@nextcloud/router.js
* Talk Desktop defines the default value for `baseUrl` in `@nextcloud/router` requests, it is it not explicitly set
* But if it's set as `undefined` or other `falsy` value, Nextcloud Talk keeps it as a set value
* It results in requesting without `baseURL`
* Solution: only set `baseURL` if it is not actually set with `truthy` value
Example of the problematic place:
https://github.com/nextcloud/spreed/blob/29af6dac6325af9bba16b4706bb09066b601165e/src/utils/signaling.js#L980-L981
=> fix(patchers): ignore unset baseURL in @nextcloud/router

src/talk/renderer/assets/overrides.css, src/talk/renderer/components/ThemeLogo.vue, src/talk/renderer/components/UiMenuItem.vue, src/talk/renderer/components/UserMenu.vue
* There was a focusable element inside another focusable element
* Some server global styles from button also have high specificity
* Made avatar a button instead of wrapping into HTML button
* Opens manually now, because floating vue doesn't support `role=button` as buttons
* Submenu is kept open after reopening the user menu
* Closed
* Menu has unlimit width
* Limited
* Server icon is not a square
* Adjusted size
* Title bar has server specificfocus-visible underline
* Removed
🏚️ Before (2 focus) | 🏡 After (1 focus)
---|---
---|---
=> fix(UserMenu): minor visual issues

src/shared/setupWebPage.js
* Federation feature seems disabled on Talk Desktop. For example, you don't see invitations
* `federation_enabled` state in initial state was not set
* It's better if frontend uses capabilities here...
=> fix: federation feature is always disabled

src/talk/talk.window.js
* Previous 1680x1050 was too huge for FHD screen (1050 + title bar > 1080 - task bar)
* With a new compact design we can make it smaller and yet fit Media Settings
* Ref: https://github.com/nextcloud/talk-desktop/pull/682
* ~~Make the window initially maximized~~
* ~~It seems like most of the users use it maximized anyway~~
* Dropped
---|---
=> fix: make Talk window more compact to fit into full HD

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v20.0.0-rc.2
- Adjust About window size and paddings [#754](https://github.com/nextcloud/talk-desktop/pull/754)
- Fix federated invitations support [#747](https://github.com/nextcloud/talk-desktop/pull/747)
- Make Talk window default size smaller with new compact design [#746](https://github.com/nextcloud/talk-desktop/pull/746)
- Fix the connection issue with losing base URL when built with Nextcloud Talk v20 [#742](https://github.com/nextcloud/talk-desktop/pull/742)
- Fix REUSE-compliance and check it on CI [#752](https://github.com/nextcloud/talk-desktop/pull/752)
- Support building with Talk 21 (Nextcloud 31) [#751](https://github.com/nextcloud/talk-desktop/pull/751)
<details>
* fix: federation feature is always disabled by @ShGKme in …
=> release: v0.35.0

src/shared/setupWebPage.js, src/talk/renderer/init.js
* The header was still visually 50px even its content and system title bar is 50px. It should be 46px.
* On screenshots see 4px gap under the minimize button
* By mistake I set height in `initLocalStyles` which is not used after another PR made that time
---|---
=> fix(talk): set --header-height

src/talk/renderer/assets/overrides.css
Unneeded after fix on upstream
=> refactor: remove --header-height set on .content

src/talk/renderer/components/UiMenuItem.vue
=> fix(UserMenu): reset default button color style

src/talk/renderer/Viewer/Viewer.js, src/talk/renderer/Viewer/ViewerHandlerText.vue
- Based on https://github.com/nextcloud/talk-desktop/pull/784
- Only the last commit is related
* A part of: https://github.com/nextcloud/talk-desktop/issues/256
Includes features:
- File types:
- `.md` with extended markdown support
- `.txt` with auto link only
- Different source code files with monospaced font (depends on the server's mimetype detection)
- Switch between 900px / fullwidth modes
- Copying text content
- Navigating/selecting like in a readonly contenteditable area
- Handling empty files
🌕 Light | 🌑 Dark
---|---
🌕 Light | 🌑 Dark
---|---
Enabled | Disabled
---|---
🌕 Light | 🌑 Dark
---|---
🌕 Light | 🌑 Dark
---|---
The text is within `contenteditable`, so a user can select/copy/navigate like in a text editor. But it is readonly.
=> feat(viewer): add Text, Markdown and Source Code viewer (read-only)

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v20.0.0-rc.4
- Add PDF Viewer [#784](https://github.com/nextcloud/talk-desktop/pull/784)
- Add Text, Markdown, and Source Code Viewer (read-only) [#785](https://github.com/nextcloud/talk-desktop/pull/785)
- Improve Viewer styling and loading/error handling [#783](https://github.com/nextcloud/talk-desktop/pull/783)
<details>
* chore: update workflows from templates by @nextcloud-command in https://github.com/nextcloud/talk-desktop/pull/765
* build(deps-dev): Bump zx from 8.1.4 to 8.1.5 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/780
* build(deps): Bump @nextcloud/vue from 8.17.0 to 8.17.1 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/779
* fix(viewer): improve styling and loading/error handling by @ShGKme in …
=> release: v0.37.0

src/authentication/renderer/AuthenticationApp.vue, src/help/renderer/HelpApp.vue, src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue, src/talk/renderer/Viewer/ViewerApp.vue, src/talk/renderer/components/DesktopMediaSourceDialog.vue, src/talk/renderer/components/DesktopMediaSourcePreview.vue, src/talk/renderer/components/MainMenu.vue, src/talk/renderer/components/UserMenu.vue, src/upgrade/renderer/UpgradeApp.vue
Small refactoring - rename icons to follow Nextcloud server and some apps convention, which is also in line with Vue style guide.
=> refactor: rename mdi components from `Mdi*` to `Icon*`

.eslintrc.js, .github/workflows/lint-typescript.yml, jsconfig.json, package-lock.json, package.json, src/global.d.ts, src/shared/globals/OC/OcDialogsAdapter.vue, src/talk/renderer/Viewer/ViewerApp.vue, src/talk/renderer/Viewer/viewer.service.ts, tsconfig.json
Adds improved TypeScript support:
- Adds `vue-tsc` to typecheck Vue components
- Adds `typecheck` npm script and `typecheck` (elint-typescript`) CI action
- Fixes `tsconfig.json` and `global.d.ts` types
- Unfortunately, `@nextcloud/vue` in v8 doesn't support Vue, so, it must be mocked with fake empty component
- Fixes TS and ESLint issues
No JS check atm. Migrating codebase to TS comes in follow-ups separated PRs.
=> chore: ts support

src/shared/setupWebPage.js
* Fix disabled typing indicator in conversations
=> fix(state): get typing privacy from capabilities

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v20.0.0
- Fix typing-status sharing being always disabled [#799](https://github.com/nextcloud/talk-desktop/pull/799)
<details>
* build(deps-dev): Bump eslint-plugin-vue from 9.27.0 to 9.28.0 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/788
* build(deps-dev): Bump eslint-plugin-import from 2.29.1 to 2.30.0 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/789
* build(deps): Bump @nextcloud/files from 3.8.0 to 3.9.0 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/790
* build(deps-dev): Bump electron from 32.0.1 to 32.0.2 by @dependabot in https://github.com/nextcloud/talk-desktop/pull/791
* refactor: rename mdi components from `Mdi*` to `Icon*` by @ShGKme in …
=> release: v0.38.0

package-lock.json, package.json
- chained on https://github.com/nextcloud/talk-desktop/pull/828
=> chore(deps): bump vue-material-design-icons to 5.3.1

.eslintrc.js, src/app/AppConfig.ts, src/authentication/authentication.window.js, src/main.js, src/preload.js, src/shared/appConfig.service.ts, src/shared/setupWebPage.js, src/talk/renderer/Settings/DesktopSettingsSection.vue, src/talk/renderer/Settings/appConfig.store.ts, src/talk/renderer/Settings/components/SettingsSelect.vue, src/talk/renderer/Settings/components/SettingsSubsection.vue, src/talk/renderer/Settings/index.ts, src/talk/renderer/Settings/useAppConfigValue.ts, src/talk/renderer/components/MainMenu.vue, src/talk/renderer/composables/useNcSelectModel.ts, src/talk/renderer/talk.main.js, src/talk/renderer/utils/createCustomElement.ts, src/talk/talk.window.js, src/welcome/welcome.window.js, tsconfig.json, webpack.main.config.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/27
Separated by commits with 💙
- Stored in a file
- Not bind to a specific user session
- Frontend API to init the config
- Store and composables to work with AppConfig
- Add a Talk Settings Section "Application"
More settings are ready and will come in a separate PR
=> feat: add application config aka settings

src/app/applyDownloadNotification.js, src/app/downloads.ts, src/app/externalLinkHandlers.js, src/main.js, src/preload.js, src/shared/setupWebPage.js, src/talk/talk.window.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/824
* Requires: https://github.com/nextcloud/spreed/pull/13618
Unfortunately, there is no better way to handle download links. Electron doesn't handle it, doesn't trigger `will-download` nor allows detecting that the link was a download link in `will-navigate`
=> feat: handle download links 

forge.config.js
* Throws an error earlier if trying to build packages after simple cloning the repo
=> fix(build): check whether spreed repository are installed in generateAssets() hook

src/main.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/845
Unlike other OS, when all windows are closed on macOS, the app is still kept running (app's menu bar is active, icon in the Dock looks like open's app icon).
New click on the Dock icon should "activate" the app and create the window again.
But the window is created hidden by default (stays in the system tray).
The fix - explicitly show the window on activate.
=> fix(app): show window on activate on macOS

src/talk/renderer/notifications/notifications.store.js
In web-browser it makes sense to show Talk logo as notification image.
But on Desktop all Talk Desktop notifications are from the Talk, and there is an application icon already.
Icon show as the notification **image** should be removed.
Also, it is always dark.
=> fix(notifications): remove notification (talk) icon from notification image

forge.config.js, package-lock.json, package.json
* Fix: https://github.com/nextcloud/talk-desktop/issues/848
1. Install [Flatpak](https://flatpak.org/setup/)
2. Get `.flatpak` file
3. Run and follow instructions (yes, password, yes, password)
```sh
flatpak install <path to .flatpak>
```
1. Install `flatpak`, `flatpak-builder`, and `elfutils`. Example for Ubuntu:
```sh
sudo apt-get install -y flatpak flatpak-builder elfutils
```
2. Run 
```sh
flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
```
3. Enable file:// protocol in git (you can disable it later, or try without it)
```sh
git config --global --add protocol.file.allow always
```
4. Follow general package steps for Linux
```sh
npm ci
npm run build
npm run package
```
=> build: add Linux flatpak

README.md, package.json, scripts/prepare-release-packages.mjs
Allows to:
- Have the built-in Talk version in the repository history
- Have a PR to explicitly bump the built-in Talk version
- Reproduce a release package with a simple `git checkout version + release:package` instead of searching in the changelog for the Talk version
- Build release on CI. Before, a Talk version was manually specified by a developer during the release
Currently, it only affects the `release:package` script used in the releases.
Follow-ups:
- Use it for repo init instead of `git clone spreed`
- Automate built-in Talk version bump
=> build: specify built-in Talk version in package.json

src/main.js
- Allows launching a new instance of Talk instead of a running one
- Prevents a situation when there is an old Talk keep running in the background instead of a new one after installation 
1. Build executable with `npm run build`
2. Copy it to a new location. now you have 2 "installations"
3. Run the first one, open some chat/settings
4. Minimize or close the window
5. Try to run the first installation again
- It should open/focus the window
6. Open the second installation
- **Before:** the first window is open instead of the new installation
- **After:** the first installation is closed and the new is launched
7. Run the second installation again
- Just to make sure it still works as expected for a single instance
=> fix(app): handle opening new installation instance

src/main.js
* Fix opening the second instance when the first one is not fully initialized (on welcome or creating a window)
* Fix opening the second instance when there are no windows in the first one (on macOS where app can run without windows)
=> fix: open second instance in edge cases

CHANGELOG.md, package-lock.json, package.json
- Add application settings [#835](https://github.com/nextcloud/talk-desktop/pull/835)
- Add monochrome tray icon setting [#836](https://github.com/nextcloud/talk-desktop/pull/836)
- Add download links handling with a new [#840](https://github.com/nextcloud/talk-desktop/pull/840)
- Add zoom setting and fix a number of zoom-related issues [#853](https://github.com/nextcloud/talk-desktop/pull/853)
- Fix error on launching app twice quickly before it initializes [#856](https://github.com/nextcloud/talk-desktop/pull/876)
- Fix focusing a window on macOS when there is no window [#856](https://github.com/nextcloud/talk-desktop/pull/876)
- Fix window Show the window on activate on macOS [#852](https://github.com/nextcloud/talk-desktop/pull/852)
- Fix Viewer close not handled during a call …
=> release: v1.0.0-rc.1

src/app/applyContextMenu.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/888
* Also remove "Copy link text" when there is no text to copy
---|---
=> feat: add "Copy email address" to context menu

src/app/AppConfig.ts
* Config path ignores the app name:
* Production and Dev instances share the same config file
* Multi-account instances share the same config
* Config is supposed to app's data directory, which depends on the name (executable)
* However, it didn't work:
* Constant with the path was defined on the module-level
* Module is executed on `require`/`import` before `app.setName()` was called and name was set
* Fix: get the name only on config load, not on module import
=> fix(config): config path ignores actual app path

src/app/AppConfig.ts, src/talk/renderer/DesktopHeader.vue, src/talk/renderer/Settings/DesktopSettingsSection.vue, src/talk/renderer/Settings/appConfig.store.ts, src/talk/renderer/Settings/useAppConfigValue.ts, src/talk/renderer/init.js, src/talk/renderer/talk.main.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/630
Desktop alternative for the following web settings (but with respect DND option):
For simple testing - check initial state
=> feat: add play sound config

forge.config.js
A small fix.
Because ENV var was checked instead of a local variable, the default value was ignored.
Allows developing without `.env` file when Talk is cloned to the `./spreed` as said in the README.
=> build: fix default TALK_PATH check

forge.config.js
Removing packaging to `zip` from macOS and Windows. This was a temp solution and 
- For macOS it's definitely unnecessary - `.dmg` is a sufficient replacement
- For Windows, I'm not so sure... But until it's directly requested, let's get rid of it
For Linux there is no universal solution that works for everyone, so keeping zip as a universal base.
Note: `.zip` wasn't a completely "portable" installation — user data was always in the user folder.
=> build: package to ZIP only for Linux

forge.config.js
Currently, distribution (installer) file names are different from different packaging tools.
This PR unifies it in a format:
```
Nextcloud.Talk-<PLATFORM>-<ARCH>.ext
```
Where platform is renamed to a user-friendly name:
- `darwin` => `macos`
- `win32` => `windows`
While it is cool to have a version in the file name, it makes it hard to have a constant link to the installer. The version is removed.
Examples:
- `Nextcloud.Talk-macos-universal.dmg`
- `Nextcloud.Talk-windows-x64.exe`
- `Nextcloud.Talk-windows-x64.msi`
- `Nextcloud.Talk-linux-x64.flatpak`
- `Nextcloud.Talk-linux-x64.zip`
All packagers have different output paths, incl. folder structure, and filenames.
In most of them, there is no option to specify or override it 😒
Hotfix: manually move files to the correct location. …
=> build: unify distribution file names

src/main.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/885
* Similar to https://github.com/nextcloud/talk-desktop/pull/852
* That PR only fixed it for closed windows like the login window
* This PR also fixes it when the window is not closed but minimized to the system tray
---
Additional changes after discussions are forked to https://github.com/nextcloud/talk-desktop/pull/911
=> fix(mac): show window on activate when minimized to tray

src/app/theme.config.ts, src/main.js, src/shared/setupWebPage.js, src/talk/renderer/Settings/appConfig.store.ts
A minor change in theming. Simplifying pages setup and respects selected theme in all parts of the app.
* Before we used Nextcloud theme via `[data-theme-*]`. It has 2 drawbacks:
* Requires setting attrs initially on every window
* Native parts of the app have a system theme
* Now using a native theme:
* Requires settings only once on app init
* Works on all the parts
Example - a Light theme on a Dark system
---|---
=> fix: apply selected theme also to native parts of the app

forge.config.js
- Adds MSI installer with Deployment Tool for administrative environment (when the app is installed using Group Policies)
- Note: the installation is still per-user in the `%User%/AppData/Local`, not `C:/Program Files/`
- Alternative to the classic MSI installer
Details: https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/machine-wide-installs.md
=> build(windows): add Squirrel MSI

CHANGELOG.md, package-lock.json, package.json
- Add new About window with an improved diagnosis report [#917](https://github.com/nextcloud/talk-desktop/pull/917)
- Add "Copy email address" to `mailto:` links context menu [#890](https://github.com/nextcloud/talk-desktop/pull/890)
- Fix light/dark theme is not applied to native parts of the app [#916](https://github.com/nextcloud/talk-desktop/pull/916)
- Fix parallel installations sharing common settings [#891](https://github.com/nextcloud/talk-desktop/pull/891)
- Fix macOS tray icon not following system style [#887](https://github.com/nextcloud/talk-desktop/pull/887)
- Fix screensharing on Flatpak distribution in Wayland [#877](https://github.com/nextcloud/talk-desktop/pull/877)
- Built-in Talk in binaries is updated to v20.1.0-rc.2 …
=> release: v1.0.0-rc.2

src/callbox/renderer/callbox.service.ts, src/talk/renderer/notifications/notifications.store.js
* Ref #961
* If there are no participants in call, call is already missed, and callbox shouldn't be shown
* If call is missed, normal notification with normal sound should be shown
---|---
Callbox all the time | "You missed a call" notification
Call ringtone | Normal beep
=> fix(callbox): check if there are no participants in call

src/talk/renderer/notifications/notifications.service.js, src/talk/renderer/notifications/notifications.store.js
* Fix #961
* Basic implementation of https://github.com/nextcloud/notifications/commit/6a543679b4de8af65cc82baa233ae17ffbbbc1af
* First fetch does not create notifications, so initial 0 should be fine
To test:
* create any Talk notification
* execute ` occ notification:test-push userid` 25 times to fill the server response
* start Desktop client
* dismiss one of dummy notifications
* wait for the next 200 response
---|---
Old notification | No notification
=> fix(notifications): do not create native notification for old entries

package-lock.json, package.json, src/shared/datetime.utils.ts, src/talk/renderer/UserStatus/components/UserStatusFormClearAt.vue, src/talk/renderer/UserStatus/userStatus.utils.ts
* `@nextcloud/moment`:
* uses unmaintained `moment`
* uses old `@nextcloud/l10n` v2
* isn't really needed in modern Chromium
=> chore: remove moment

CHANGELOG.md, package-lock.json, package.json
**Squirrel Deployment Tool .msi → WiX v3 .msi**:\
Experimental MSI installer with Squirrel Deployment Tool is removed
and replaced with a new MSI installer based on WiX v3.
You may remove the old installation. Your settings will be preserved.  
- Add a new MSI installer based on WiX v3 for Windows [#1103](https://github.com/nextcloud/talk-desktop/pull/1103)
- Add an option to repeat call notification sound on a second output device [#772](https://github.com/nextcloud/talk-desktop/issues/772)
- Fix call notification is still active when the call is joined [#1117](https://github.com/nextcloud/talk-desktop/issues/1117)
- Built-in Talk in binaries is updated to v21.0.0-rc.4 in the beta release channel [#1119](https://github.com/nextcloud/talk-desktop/pull/1119)
- Click five times on the logo …
=> release: v1.1.4 beta

src/shared/setupWebPage.js
* Follow-up to https://github.com/nextcloud/spreed/pull/14447
🏡 After
=> fix: set circles_enabled in initial state from server capabilities

src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue
* Hotfix for emoji picker focus trap
* Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6466
* A proper solution on the nextcloud-vue side is in progress
---|---
=> fix(user-status): emoji picker cannot be focused

CHANGELOG.md, package-lock.json, package.json
- Loop ringtone on incoming call [#1123](https://github.com/nextcloud/talk-desktop/pull/1123)
- Teams (Circles) support [#1121](https://github.com/nextcloud/talk-desktop/pull/1121)
- Built-in Talk in binaries is updated to v21.0.0 in both beta and stable release channels [#1137](https://github.com/nextcloud/talk-desktop/pull/1137)
- Update translations
- Update dependencies
=> release: v1.1.5

src/shared/setupWebPage.js
* Issue #985
* appData.userMetadata might have a locale as `" "` empty string (which means user has never changed it in Personal settings), but it won't be replaced with system value and handled by system as empty string
* `Intl.*` constructors do not accept empty string as a locale:
=> fix: substitute empty locale from server with system locale

eslint.config.mjs, forge.config.js, src/app/appProtocol.ts, src/app/externalLinkHandlers.ts, src/app/utils.ts, src/app/webRequestInterceptor.js, src/authentication/authentication.window.js, src/callbox/callbox.window.ts, src/constants.js, src/global.d.ts, src/help/help.window.js, src/main.js, src/talk/renderer/talk.main.ts, src/talk/talk.window.js, src/upgrade/upgrade.window.ts, src/welcome/welcome.window.js
* For https://github.com/nextcloud/talk-desktop/issues/9
* 18: https://www.electronjs.org/docs/latest/tutorial/security#18-avoid-usage-of-the-file-protocol-and-prefer-usage-of-custom-protocols
* Base for:
* Some other improvements
* https://github.com/nextcloud/talk-desktop/issues/387
Note, it's only an internal protocol. It is not exposed to the system (yet).
Resources where loaded via `file://` protocol and absolute file path.
There is an internal application protocol with the following URLs:
- `nctalk://app/` - Application files
- `nctalk://app/welcome_window/index.html` - welcome page
- `nctalk://app/talk_window/index.html` - Talk
- `nctalk://app/talk_window/index.js` - static file
- etc.
- `nctalk://call/{token}/` - Link to a specific conversation
- Redirects to …
=> chore: add internal app protocol

CHANGELOG.md, package-lock.json, package.json
- Add untrusted SSL certificate support on Linux [#1200](https://github.com/nextcloud/talk-desktop/pull/1200)
- Built-in Talk in binaries is updated to v21.0.2 in both beta and stable release channels [#1224](https://github.com/nextcloud/talk-desktop/pull/1224)
- Update translations
- Update dependencies
=> release: v1.1.7

src/talk/renderer/TitleBar/components/UserMenu.vue, src/talk/renderer/UserStatus/UserStatusDialog.vue, src/talk/renderer/UserStatus/components/UserStatusForm.vue, src/talk/renderer/UserStatus/components/UserStatusFormBackup.vue, src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue, src/talk/renderer/UserStatus/components/UserStatusFormPredefinedOption.vue, src/talk/renderer/UserStatus/predefinedStatuses.store.ts, src/talk/renderer/UserStatus/userStatus.store.ts
* Fix: https://github.com/nextcloud/talk-desktop/issues/1233
* Before backup status was requested on each heartbeat
* After it is requested only before opening the user status form
* Also:
* Removed user status request from User Menu's avatar — use preload status
* Fix the backup status design, as it is now more visible (I'm fine with dropping this commit)
* Refactored a bit:
* Decompose predefined statuses from the user status store
* Use `useBrowserStorage` for LS caching
---|---
=> perf(user-status): do not request backup status until user status form open

src/app/appProtocol.ts, src/app/webRequestInterceptor.js, src/authentication/renderer/AuthenticationApp.vue, src/main.js, src/shared/setupWebPage.js, src/welcome/welcome.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/1234
* The app is on `nctalk://app` host
* The server is on `https://some.nextcloud.ltd`
* Request from the app to the server is a cross-origin request (forbidden)
* In the past was "allowed" by changing the server response
* This still makes an unnecessary server request
* Now it redirects to internal `ncapp://api/https://some.nextcloud.ltd` and proxies the request
* It still has an ugly redirect
* But no `OPTIONS` requests to the server
---|---
=> fix: avoid preflight (OPTIONS) request by using internal reverse proxy

src/main.js, src/shared/setupWebPage.js
* In Nextcloud we use the posix format (e.g. `en_US`) while HTML expects IETF (`en-US`)
* This results in errors in `Intl`
* Fix: https://github.com/nextcloud/talk-desktop/issues/985
=> fix(app): errors due to incorrect language format

forge.config.js
* Fix https://github.com/nextcloud/talk-desktop/issues/1209
* It was fixed because I renamed files manually after the build 🙈
* Regression from https://github.com/nextcloud/talk-desktop/pull/1193
* There were different sanitized name formats...
* In dist files we used `.` as a replacement of non-alphanumeric characters
* In other places - non-alphanumeric characters are just removed
=> build: use dot in sanitized dist name

src/shared/globals/OC/mimetype.js
* Issue #1253
* 'dir' is not listed anywhere, but 'folder' exists
---|---
=> fix: adjust mimetype icon for directories

src/install-vue-devtools.js
* Follow-up: https://github.com/nextcloud/talk-desktop/pull/1272
* Fix deprecation:
> Moved Session extension APIs to Session.extensions. [#45597](https://redirect.github.com/electron/electron/pull/45597)
=> chore: migrate to Electron 36 `session.extensions`

CHANGELOG.md, package-lock.json, package.json
- Regression breaking connection to Nextcloud server with non-empty base URL [#1263](https://github.com/nextcloud/talk-desktop/issues/1263)
- Update translations
- Update dependencies
=> release: v1.1.9

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v21.1.0-rc.1 in the beta release channel [#1286](https://github.com/nextcloud/talk-desktop/pull/1286)
=> release: v1.2.0-beta

src/main.js
- Fix: https://github.com/nextcloud/talk-desktop/issues/1289
- Tested on Fedora 39
=> fix(linux): crash with GTK version error on GNOME

package.json
Stable:
- Current: v21.0.4
- Latest: v21.0.4
Beta:
- Current: v21.1.0-rc.1
- Latest: v21.1.0-rc.2
Updating beta from v21.1.0-rc.1 to v21.1.0-rc.2
=> build: update built-in Talk versions

CHANGELOG.md, package-lock.json, package.json
- Crash with GTK version error on Linux with GNOME [#1290](https://github.com/nextcloud/talk-desktop/pull/1290)
- Built-in Talk in binaries is updated to v21.1.0-rc.2 in the beta release channel [#1298](https://github.com/nextcloud/talk-desktop/pull/1298)
=> release: v1.2.1-beta

src/talk/renderer/TitleBar/TitleBar.vue
- Not needed with the new dashboard and explicit Home button
=> fix(title-bar): remove logo click in favor of new home button

src/app/appData.service.js, src/welcome/welcome.js
- Fix: https://github.com/nextcloud/talk-desktop/issues/1167
- Always re-fetch capabilities and user metadata on application launch
- Before it was only refetched on dirty hash and talk desktop update
=> fix(app): always re-fetch capabilities and user data on launch

src/app/system.utils.ts, src/main.js
- Fix: https://github.com/nextcloud/talk-desktop/issues/1091
- In flatpak execPath is determined as relative to the home directory instead of an actual exec path inside the sandbox
- This path does not only break same installation check but also breaks new instance execution as the path is not valid to run the app
- There could be no 2 Nextcloud Talk apps inside a single sandbox
- For Flatpak - comparing FLATPAK_ID instead of the exec path
=> fix(linux/flatpak): second instance detection

src/talk/renderer/TalkWrapper/talk.service.ts
- Missed during Vue 3 migration
=> fix(title-bar): open in web link is broken

package.json
Stable:
- Current: v21.1.0
- Latest: v21.1.1
Beta:
- Current: v21.1.0
- Latest: v21.1.1
Updating stable from v21.1.0 to v21.1.1
Updating beta from v21.1.0 to v21.1.1
=> [stable1] build: update built-in Talk versions

package-lock.json, package.json
- Quit button in the user menu [#1356](https://github.com/nextcloud/talk-desktop/pull/1356)
- Re-opening application while running in background is broken on Linux in Flatpak [#1358](https://github.com/nextcloud/talk-desktop/pull/1358)
- Built-in Talk in binaries is updated to v21.1.1 in both beta and stable release channels [#1365](https://github.com/nextcloud/talk-desktop/pull/1365)
=> release: v1.2.4

src/authentication/authentication.window.js, src/authentication/login.window.js, src/authentication/renderer/authentication.main.js, src/certificate/certificate.window.ts, src/certificate/renderer/certificate.main.ts, src/help/help.window.js, src/help/renderer/help.app.js, src/main.js, src/preload.js, src/shared/setupWebPage.js, src/upgrade/renderer/upgrade.main.ts, src/upgrade/upgrade.window.ts
- Fix: https://github.com/nextcloud/talk-desktop/issues/1373
Electron keeps the window title on reload instead of using the initial title from Window options.
As a result, using the current window title as the base title on reload results in a duplicated title on reload.
There is no way to get the original title from window options. Instead - move the title setting to the renderer side.
It also allows translating the title.
=> fix(app): window title is untranslated and may duplicate on reload

src/callbox/renderer/CallboxApp.vue, src/talk/renderer/TitleBar/components/MainMenu.vue, src/talk/renderer/TitleBar/components/UserMenu.vue, src/upgrade/renderer/UpgradeApp.vue
=> fix: use outline icons

src/shared/setupWebPage.js
- Found from checking https://github.com/nextcloud/spreed/pull/15533
- appData has the required information, so should be fine to put it into initial state
=> fix: get app version for initial state from app data

package-lock.json, package.json
Update dependencies on `stable1`.
The most important is electron ^36.5.0 → ^37.2.3.
This includes the new Chromium release and might help with the following issue: https://issues.chromium.org/issues/414842421
=> [stable1] chore(deps): update deps, including electron ^36.5.0 → ^37.2.3

CHANGELOG.md
- Logout and Quit buttons do nothing [#1378](https://github.com/nextcloud/talk-desktop/pull/1378)
- Built-in Talk in binaries is updated to v21.1.2 in both beta and stable release channels [#1384](https://github.com/nextcloud/talk-desktop/pull/1384)
- Electron is updated to 37, including Chromium 138 [#1382](https://github.com/nextcloud/talk-desktop/pull/1382)
=> chore(release): add v1.2.5 changelog

package-lock.json, package.json, src/authentication/renderer/AuthenticationApp.vue, src/talk/renderer/TitleBar/components/DevMenu.vue, src/talk/renderer/TitleBar/components/MainMenu.vue, src/talk/renderer/Viewer/ViewerHandlerBase.vue, src/talk/renderer/screensharing/DesktopMediaSourceDialog.vue
- Mostly minor bump
- `npm audit fix`
- Bump Electron from 36 to 37
- No relevant breaking changes: https://releases.electronjs.org/release/v37.0.0
=> chore: update dependencies

src/talk/renderer/TitleBar/components/UserMenu.vue, src/talk/renderer/UserStatus/userStatus.utils.ts
I'm lasy, it's the same screenshot
=> feat(user_status): add 'Busy' status support

src/talk/renderer/screensharing/getDesktopMediaSource.ts
The type wasn't defined and used in
```ts
let appGetDesktopMediaSourceInstance: InstanceType<typeof AppGetDesktopMediaSource> | null = null
```
=> chore(ts): fix error in getDesktopMediaSource.ts

CHANGELOG.md, package-lock.json, package.json
- Built-in Talk in binaries is updated to v22.0.0-rc.1 in the beta release channel [#1452](https://github.com/nextcloud/talk-desktop/pull/1452)
- Built-in styles were updated to Nextcloud v32.0.0rc1 styles [#1451](https://github.com/nextcloud/talk-desktop/pull/1451)
- Talk Desktop is migrated Vue 3 and can no longer use built-in Talk below v22 with Vue 2 [#680](https://github.com/nextcloud/talk-desktop/pull/680), [#1422](https://github.com/nextcloud/talk-desktop/pull/1422)
=> release: v2.0.0-beta

CHANGELOG.md, package-lock.json, package.json
- Experimental fix for video streams [#1478](https://github.com/nextcloud/talk-desktop/pull/1478)
- Built-in Talk in binaries is updated to v22.0.0 in both beta and stable release channels [#1480](https://github.com/nextcloud/talk-desktop/pull/1480)
=> release: v2.0.2
