- package.json
- Fix zoom without SHIFT and by mouse wheel (#77)
- Fix wrong display name in calls and temp messages (#72)
- Fix loosing authentication on notify_push on any ws error caused brute force protection (#76)
Also, [Talk 16.0.1](https://github.com/nextcloud/spreed/releases/tag/v16.0.1) is released
> release: v0.2.2

- .github/dependabot.yml
Fix: https://github.com/nextcloud/talk-desktop/pull/68/checks?check_run_id=12320748163
> chore(deps): fix dependabot.yml

- .l10nignore
- .tx/config
- src/talk/renderer/components/UserMenu.vue
- src/talk/renderer/desktop.app.js
- src/talk/renderer/init.js
Apply this diff:
```diff
diff --git a/src/shared/ocs.service.js b/src/shared/ocs.service.js
index ae69b87..8d03dda 100644
--- a/src/shared/ocs.service.js
+++ b/src/shared/ocs.service.js
@@ -45,7 +45,9 @@ export async function getCapabilities() {
*/
export async function getUserMetadata({ userId }) {
const response = await axios.get(generateOcsUrl('cloud/users/{userId}', { userId }))
-       return response.data.ocs.data
+       const data = response.data.ocs.data
+       data.language = 'br'
+       return data
}
/**
@@ -57,5 +59,7 @@ export async function getUserMetadata({ userId }) {
*/
export async function getCurrentUserData() {
const response = await axios.get(generateOcsUrl('cloud/user'))
-       return response.data.ocs.data
+       const data = response.data.ocs.data
+ …
```
> fix(l10n): 🔣 Set up translations

- .github/workflows/lint-eslint.yml
> Set up lint-eslint.yml github action

- package-lock.json
- package.json
- src/app/githubReleaseNotification.service.js
- src/main.js
* Issue #84 
Every 2h checks if there is a new release on GitHub releases and notify with a push notification. Click on the notification opens the latest release page.
> New release notification

- src/app/applyContextMenu.js
- src/app/applyDownloadNotification.js
- src/authentication/authentication.window.js
- src/authentication/login.window.js
- src/talk/talk.window.js
* Close #44
* Close #58 
* Close #110 
https://user-images.githubusercontent.com/93392545/229553053-c53e89b5-33f7-4730-b2cd-f28baf0f9fc1.mp4
> Add native context menu

- src/app/appData.service.js
> fix: do not destruct JSON from import

- README.md
- package-lock.json
- package.json
- scripts/prepare-release-packages.mjs
_(Steps count are incorrect on the gif, fixed)_
- Check that there are no uncommitted changes
- Clone Talk if needed to `speed`, checkout tag
- Install all dependencies
- Package
> Add release scripts

- .github/workflows/fixup.yml
* Issue https://github.com/nextcloud/talk-desktop/pull/349#issuecomment-1721024833
> chore(ci): add Block fixup workflow

- src/authentication/renderer/AuthenticationApp.vue
> fix(i18n): Triple to to ellipsis

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v18.0.0
> release: v0.19.0

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v18.0.3
> release: v0.21.0

- src/authentication/authentication.window.js
- src/authentication/login.window.js
- src/help/help.window.js
- src/shared/icons.utils.js
- src/talk/talk.window.js
- src/upgrade/upgrade.window.js
- src/welcome/welcome.window.js
* Issue #53
---|---
B | A
| ![grafik](https://github.com/nextcloud/talk-desktop/assets/1479486/c5bb8ba6-aa24-4f9c-b8e8-5dbaf7b6c7c7) | ![grafik](https://github.com/nextcloud/talk-desktop/assets/1479486/d86a7af7-f829-447d-8547-0ef36d8a1aa5) |
> fix: window icons on linux

- src/app/webRequestInterceptor.js
* It is not possible to upload an image
> fix(app): allow X-OC-MTIME header for uploading

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v19.0.0-beta.2
> release: v0.24.0

- README.md
Some things I stumbled over :see_no_evil:
> fix(docs): Improve release docs

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v19.0.0-beta.5
> Release v0.26.0

- .github/dependabot.yml
- package-lock.json
- package.json
> fix(deps): Downgrade undici again

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v19.0.0-rc.1
> Release v0.27.0

- README.md
- src/talk/renderer/Viewer/Viewer.js
- src/talk/renderer/Viewer/ViewerApp.vue
- src/talk/renderer/Viewer/ViewerHandlerImages.vue
- src/talk/renderer/Viewer/ViewerHandlerVideos.vue
- src/talk/renderer/talk.main.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/255
> feat: Image Viewer

- src/shared/globals/globals.js
* Fix https://github.com/nextcloud/talk-desktop/issues/605
> fix: prettify links by using actual modRewriteWorking from capabilities for Nextcloud 29+

- src/main.js
* Previously, after logging in the main window was minimized to the system tray
* Now it is opened
* No changes for launching app being logged in
> fix: show main window after login

- README.md
> chore(README): remove user status from unsupported features list

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v19.0.4
> release: v0.31.0

- src/authentication/authentication.window.js
- src/talk/talk.window.js
- src/welcome/welcome.window.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/734
> fix: disable custom title bar on Linux

- src/talk/renderer/assets/overrides.css
> fix(talk): increase overrides styles specificity

- src/help/renderer/HelpApp.vue
> fix(help): adjust paddings and elements size

- CHANGELOG.md
- package-lock.json
- package.json
- Built-in Talk in binaries is updated to v20.0.1
> release: v0.39.0

- src/talk/renderer/Viewer/Viewer.js
* Follow-up to #https://github.com/nextcloud/spreed/pull/13504
> fix(Viewer): expose Viewer.mimetypes as unified array of supported mimes

- forge.config.js
> fix(flatpak): screen sharing on Wayland

- forge.config.js
* Fix: https://github.com/nextcloud/talk-desktop/issues/882
> build(flatpak): update runtime and base

- REUSE.toml
- forge.config.js
- resources/macos/entitlements.plist
- fix: https://github.com/nextcloud/talk-desktop/issues/42
> build: sign

- .github/workflows/lint-typescript.yml
* https://github.com/nextcloud/talk-desktop/actions/runs/11972026783/job/33378708164
> chore(ci): don't check typecheck result without the check

- README.md
⚠️ Merge after `1.0.0-rc.2` release ⚠️ 
---
All binaries are available on [Nextcloud Releases](https://github.com/nextcloud-releases/talk-desktop/releases).
| Platform (architecture)              | Distribution type                                                                                                                                     | Download link                                                                                                                                        |
|--------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------- …
> chore(README): add install links

- webpack.renderer.config.js
* `git describe` might be confusing:
* `g` prefix in `gHASH` specifying "git SCM" might be confusing for those who are not familiar with `git describe`
* Version from the last tagged commit doesn't include the currently developed version, for example, it shows `20.0.0-beta.3` for `main`, even when there is `20.1.0-rc.2` on the stable branch and `21.0.0-dev.0` is currently being developed
* The number of commits since the last branch is useless (0 for non-detached, and kind of a random value for detached)
* `head/` is not useful for branches
Display the version for tagged commits.
Display `version-hash (branch)` for untagged.
---|---
> fix(help): improve version description in report

- src/main.js
Improved solution is planned for 1.1.0
> chore: increase update available notify interval from 2h to 24h

- src/app/AppConfig.ts
- src/talk/renderer/Settings/DesktopSettingsSection.vue
- src/talk/renderer/Settings/components/SettingsFormGroup.vue
- src/talk/renderer/Settings/components/SettingsSelect.vue
- src/talk/renderer/composables/useNcSelectModel.ts
- src/talk/renderer/notifications/notifications.store.js
* Fix #772
* Copy from Notifications app
---|---
B | ![image](https://github.com/user-attachments/assets/f56d4450-1196-4cfc-8689-59479c94ecef)
a | ![image](https://github.com/user-attachments/assets/249eb755-c4a5-4b2a-9900-70ca95c0945a)
a | ![image](https://github.com/user-attachments/assets/4f3a3e05-b9d7-4143-969e-d29b18e1da1a)
> feat(notifications): play call notification sound on second output device

- package-lock.json
- package.json
- src/callbox/callbox.window.ts
- src/callbox/renderer/CallboxApp.vue
- src/callbox/renderer/callbox.utils.ts
- src/talk/renderer/TitleBar/components/DevMenu.vue
- src/talk/renderer/notifications/notifications.store.js
* Fix https://github.com/nextcloud/talk-desktop/issues/1116
* Added devmode trigger for the call box
* Moved call ringtone to the callbox
* No ringtone with a simple notification anymore (as expected)
* Loop the ringtone
> fix(callbox): loop ringtone

- src/talk/renderer/TalkDesktop.vue
* ref https://github.com/nextcloud/spreed/pull/14541
> fix(talk): remove escape hotkey as it's added in Talk

- src/app/AppConfig.ts
- src/main.js
> Add custom showCertificateTrustDialog for Linux

- README.md
> chore(README): add `choco`

- .github/ISSUE_TEMPLATE/bug_report.md
> Improve bug_report.md template

- src/talk/renderer/TitleBar/components/MainMenu.vue
- src/talk/renderer/Viewer/ViewerApp.vue
- src/upgrade/renderer/UpgradeApp.vue
> fix(i18n): Spelling of web browser

- .github/workflows/update-built-in-talk.yml
> ci: Try to use the nextcloud command bot for the pull request

- package-lock.json
- package.json
- Fix: #…
- Tested
---|---
B | A
> chore(deps): bump @nextcloud/vue from 8.26.1 to 8.27.0

- README.md
Added Homebrew to Install List
> Added Homebrew to README.md

- package-lock.json
- package.json
- scripts/download-vue-devtools.mjs
- scripts/vue-devtools-extension-id.mjs
- src/help/renderer/ButtonCopy.vue
- src/install-vue-devtools.js
- src/main.js
- src/talk/renderer/Settings/components/SettingsSelect.vue
- src/talk/renderer/TalkWrapper/TalkWrapper.vue
- src/talk/renderer/TitleBar/components/ThemeLogo.vue
- src/talk/renderer/TitleBar/components/UiMenuItem.vue
- src/talk/renderer/TitleBar/components/UserMenu.vue
- src/talk/renderer/UserStatus/UserStatusDialog.vue
- src/talk/renderer/UserStatus/components/UserStatusForm.vue
- src/talk/renderer/UserStatus/components/UserStatusFormBackup.vue
- src/talk/renderer/UserStatus/components/UserStatusFormClearAt.vue
- src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue
- src/talk/renderer/UserStatus/components/UserStatusFormPredefinedOption.vue
- src/talk/renderer/UserStatus/components/UserStatusFormStatusType.vue
- src/talk/renderer/Viewer/ViewerHandlerPdf.vue
- src/talk/renderer/Viewer/ViewerHandlerText.vue
- src/talk/renderer/Viewer/viewer.composables.ts
- src/talk/renderer/screensharing/DesktopMediaSourceDialog.vue
- src/talk/renderer/screensharing/DesktopMediaSourcePreview.vue
- src/talk/renderer/screensharing/DesktopMediaSourcePreviewLive.vue
- Split from https://github.com/nextcloud/talk-desktop/pull/680
- Migrate from Vue 2.7/3.2 API to Vue 3.5
- Migrate from vue-devtools-legacy to new vue-devtools
> chore(vue3): post migration

- src/talk/renderer/TitleBar/TitleBar.vue
- src/talk/renderer/TitleBar/components/UserMenu.vue
- Additional place to quit the app
> feat: add Quit button to the user menu

- package.json
Stable:
- Current: v21.1.0
- Latest: main
Beta:
- Current: v21.1.0
- Latest: main
Updating stable from v21.1.0 to main
Updating beta from v21.1.0 to main
> build: update built-in Talk versions

- src/talk/renderer/TitleBar/components/UserMenu.vue
- Regression from backport: https://github.com/nextcloud/talk-desktop/pull/1364
- Vue 2 vs Vue 3 difference
> fix(title-bar): logout and quit buttons do not work

- package-lock.json
- package.json
- Fix: status icon colors, input styles
> chore(deps): bump nextcloud/vue library to v9.0.0-rc.7

- package-lock.json
- package.json
- Fix: `__VUE_PROD_HYDRATION_MISMATCH_DETAILS__ is not defined`
> chore(deps): update vue from 3.5.19 to 3.5.20

- src/app/appProtocol.ts
- Might fix:
- https://github.com/nextcloud/talk-desktop/issues/1476
- https://github.com/nextcloud/talk-desktop/issues/1429
- https://github.com/nextcloud/talk-desktop/issues/1461
- https://github.com/nextcloud/talk-desktop/issues/1401
> fix(app): support network streams
